export * from "./pages/admin";
export * from "./pages/board";
export * from "./pages/boards";
export * from "./pages/boardSearch";
export * from "./pages/home";
export * from "./pages/idReference";
export * from "./pages/posts";
export * from "./pages/reference";
export * from "./pages/thread";