version: '3'
services:
  dev:
    build: .
    restart: "never"
    volumes:
      - .:/dapp
    ports:
      - 127.0.0.1:4444:4444

  www:
    image: httpd:2.4
    restart: unless-stopped
    volumes:
      - "$PWD/build:/usr/local/apache2/htdocs/"
    ports:
      - 127.0.0.1:59332:80
